### ISSUE TITLE
3D model Joints are at angle in hands and leg for person standing straight.

### ISSUE THREAD

**Issue by vijay1131** [akanazawa/hmr#28]
I am looking at the 3d mesh generated for person standing straight but 3d Model is not straight at hand and leg. Can this be solved?

images are attached.
![hmr1](https://user-images.githubusercontent.com/10431152/44989550-d99ccb00-afab-11e8-8e2f-b3939f5e643c.png)
![hmr2](https://user-images.githubusercontent.com/10431152/44989551-d99ccb00-afab-11e8-8231-eaa52728bf1a.png)

**Comment by akanazawa** [comment]
This is an ambiguity that is (surprisingly) hard to resolve from a single-view image, mostly because a lot of the times in the datsets knees and elbows are bent.  Straight knees and elbows are in the long tail region of the joint angle distribution.  

If you want to manually fix this for your purposes, you could set the pose values to be 0 and it will be straight.

Pose is 72-D, reshape it to 24x3, which corresponds to the axis-angle 3D representation of each joints. The order of the 24 joints are:
```
smpl_pose_names = ['Root', 'Left_Hip', 'Right_Hip', 'Waist', 'Left_Knee', 'Right_Knee', 'Upper_Waist', 'Left_Ankle', 'Right_Ankle', 'Chest', 'Left_Toe', 'Right_Toe', 'Base_Neck', 'Left_Shoulder', 'Right_Shoulder', 'Upper_Neck', 'Left_Arm', 'Right_Arm', 'Left_Elbow', 'Right_Elbow', 'Left_Wrist', 'Right_Wrist', 'Left_Finger', 'Right_Finger']
```
So for eg. if you set the 4th and 5th rows to be all 0s `pose[4:6, :] = 0.`, the left and right knee will be straight.

**Comment by Superlee506** [comment]
@akanazawa 
Hi akanazawa, the 3 following  questions confused me, I would appreciate it if you could give some suggestions:
1. What's the global coordinate of the SMPL, and what's the X, Y, Z axis?
2. Is the golbal  coordinate of the SMPL the same with g3d labels's in human3.6M and other motion datasets?
3. Because the head joint is not given above and how can I get height of a person?

**Comment by akanazawa** [comment]
Hi,

1. It's in some global coordinate frame, I forget exactly what the coordinate frame is now, best way is to plot/visualize SMPL at 0 configurations.
2. It's not the same, everybody works in their own coordinate frames. For training the model I have aligned the data, except there's a small fix you need to do to rectify the global pose. See [this issue](https://github.com/akanazawa/hmr/issues/50#issuecomment-456512570). 
3. Using the [regressor you can get the head point from SMPL](https://github.com/akanazawa/hmr/blob/537f1b2c91beb71cb61a388bf8f6504516b875a8/src/tf_smpl/batch_smpl.py#L75) or alternatively if you just want to get the height you can find the min/max point on the mesh with 0 pose. However note that getting absolute scale from a single image is still a very challenging problem. This data also does not really exist in the training set either, so YMMV in terms of quality.

**Comment by Superlee506** [comment]
@akanazawa For SMPL at 0 configuration, are the pose(72-D) and shape (10-D) params all zero?

**Comment by ayjabia** [comment]
I was able to plot the skeleton according to joints3d. How can I project it onto the original image?
When projecting onto the z axis, I get a slightly rotated skeleton relative to the image.
