### ISSUE TITLE
Is there a file missing?

### ISSUE THREAD

**Issue by kebwi** [akanazawa/hmr#58]
The documentation at the top of demo.py suggests that there ought to be a file at data/random_keypoints.json but I see no such file, only the images. Shouldn't random.jpg have been accompanied by the associated openpose output? Isn't the entire point of that image, with its larger-than-expected central figure and corresponding incorrect bounding box?

The most perplexing thing isn't the missing file. It's that the demo seems to work fine on that image anyway, so why would the openpose file be needed in the first place? I suspect this is because the demo resizes the image to the necessary smaller size anyway, but then what is the point of the openpose option? I can see how it would apply if the person wasn't about 150px after downsizing the image, but in the case of random.jpg, that doesn't appear to be the case. Is it just not a particularly good image to demonstrate the necessity and utilization of applying an openpose bounding box? Or am I misunderstanding the situation?

Thanks.

**Comment by akanazawa** [comment]
Hi,

Thanks, that file was missing, I meant to add it, but missed it bc .gitignore filtered it, thanks for reporting!

The reason why it worked was prob because in that image the person is big and centered enough. It's always better though to properly scale and translate the person to be at the center though, because regression based predictions are not so robust at unseen scales and translation. 


Best,

Angjoo
