### ISSUE TITLE
How to use 3d key points  to fit the human model

### ISSUE THREAD

**Issue by zhanghr123** [akanazawa/hmr#61]
Hello, I am very interested in your project. I found that fitting a human body shape and posture from a single picture works well. But the effect is not very good when applied to the video. Your recent work, Learning 3D Human Dynamics from Video, I am also learning.I recently saw some work, such as https://github.com/facebookresearch/VideoPose3D. I would like to ask you how to apply 3D key points to the smpl model.I look forward to your reply.

**Comment by akanazawa** [comment]
You could always try to fit SMPL to 3D joints (take the approach of [SMPLify](http://smplify.is.tue.mpg.de/), but think of 3D joint input instead of 2D), but I have never tried this. 
The video fitting code for our siggraph paper is coming, as well as the recent paper hopefully soon, so stay tuned! Thanks!

**Comment by davidpagnon** [comment]
I'm also interested, if anyone knows of any approach to this end!
