### ISSUE TITLE
When I  trained the model with my own 3d motion data, the logged images upside down.

### ISSUE THREAD

**Issue by Superlee506** [akanazawa/hmr#67]
I get the g3d using motion capture, and I'm sure the orientation of Y-axis is the same with SMPL, but when I trained the model with my own dataset, the logged images is becoming worse and upside down.
I'm not sure if it's related to the [Issue 50](https://github.com/akanazawa/hmr/issues/50#issuecomment-456512570). Any suggestion would be appreciated. Thanks.

**Comment by Superlee506** [comment]
After training.png
![individualimage](https://user-images.githubusercontent.com/13114675/51804446-fc51b800-229b-11e9-9ec2-5405ff3d08b4.png)
At the beginning of the train
![At the beginning of the train](https://user-images.githubusercontent.com/13114675/51804447-fc51b800-229b-11e9-9001-8afb78bb7af6.png)

**Comment by MatthewD1993** [comment]
Yes, it's related to the issue #50.

**Comment by akanazawa** [comment]
I'm not too sure if it's related to that issue, that definitely can contribute, and you can try to rectify the data as I describe there, but even with that one parameter being upside down it works bc everything else points to the right orientation. 

I think the issue is that the you shouldn't align the y-axis with SMPL, but make sure that they are aligned with the image coordinate system, so head Y < toe Y. Because the projection we use is a simple scaled orthographic model. 
Make sure that when you project the 3D joints with a very simple camera like [1, 0, 0] (1 scale, 0 translation), it looks up right in the image.
