### ISSUE TITLE
 TypeError: `default_name` type (<type 'list'>) is not a string type.

### ISSUE THREAD

**Issue by StatML** [akanazawa/hmr#69]
Hi,  I met a TypeError when running the following command. I am using TF 1.12, Ubuntu 18.04. Does anyone know how to fix it? Thx!

`python demo.py --img_path data/02796.jpg`

> Traceback (most recent call last):
>   File "demo.py", line 147, in <module>
>     main(config.img_path, config.json_path)
>   File "demo.py", line 121, in main
>     model = RunModel(config, sess=sess)
>   File "hmr/src/RunModel.py", line 62, in __init__
>     self.build_test_model_ief()
>   File "hmr/src/RunModel.py", line 82, in build_test_model_ief
>     reuse=False)
>   File "hmr/src/models.py", line 40, in Encoder_resnet
>     with tf.name_scope("Encoder_resnet", [x]):
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 6223, in __init__
>     % type(default_name))
> TypeError: `default_name` type (<type 'list'>) is not a string type. You likely meant to pass this into the `values` kwarg.

**Comment by SEUNGGWANSHIN** [comment]
why this topic is closed?

**Comment by A7ocin** [comment]
Hi, did you solve this? @StatML

**Comment by timctran** [comment]
Using the TensorFlow documentation for [tf.name_scope](https://www.tensorflow.org/api_docs/python/tf/name_scope), I resolved the issue by prepending `[x]` with `values=`. That is change `with tf.name_scope("Encoder_resnet", [x]):` to `with tf.name_scope("Encoder_resnet", values=[x]):`. This error also occurs in a few places over in `batch_lbs.py` which I fixed in the same way.

**Comment by alon1samuel** [comment]
I also had to change it in Ubuntu 18.04 with Tensorflow-gpu==1.14.0. Apparently it's a problem with Tensorflow>=1.12

**Comment by alon1samuel** [comment]
Maybe this bug can be fixed for tensorflow-gpu>=1.12?
